datadog:
  site: datadoghq.eu
  apiKeyExistingSecret: datadog-secret

  logs:
    enabled: true
    containerCollectAll: true

  apm:
    enabled: true
    instrumentation:
      enabled: true

  serviceMonitoring:
    enabled: true

  networkMonitoring:
    enabled: true

  processAgent:
    enabled: true

  containerRuntime:
    enabled: true

systemProbe:
  enabled: true
  sysctlEnabled: true
  seccompProfileEnabled: false
  appArmorProfileEnabled: false

admissionController:
  enabled: true
  mutateUnlabelled: true
  failurePolicy: Ignore

clusterAgent:
  enabled: true
